language: python
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements.txt"
script: nosetests
services:
  - mongodb

before_script:
  - mongo harrybotter --eval 'db.createCollection("users");'