webhook_url: YOUR-FB-APP-WEBHOOK-URL-WITHOUT-DOMAIN
messenger_access_token: YOUR-FB-MESSENGER-ACCESS-TOKEN
wolfram_appid: YOUR-WOLFRAMALPHA-APPID
adfly_public_key: YOUR-ADFLY-PUBLIC-KEY
adfly_user_id: YOUR-ADFLY-USER-ID
forecastio_api_key: YOUR-FORECASTIO-API-KEY
yandex_translate_key: YOUR-YANDEX-TRANSLATE-KEY
fullchain: PATH-TO-CERTFILE
privkey: PATH-TO-KEYFILE
languages:
  russian:
    lang_install_success: Выбран русский язык
  english:
    lang_install_success: English language is selected